// Code generated by bpf2go; DO NOT EDIT.

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type firewallCounterValue struct {
	_       structs.HostLayout
	Packets uint64
	Bytes   uint64
}

type firewallIpv4LpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      uint32
}

type firewallPortRuleKey struct {
	_        structs.HostLayout
	Protocol uint8
	_        [1]byte
	Dport    uint16
	Dst      uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	firewallMapBlockedIps    = "blocked_ips"
	firewallMapCounters      = "counters"
	firewallMapPortPolicy    = "port_policy"
	firewallProgFirewallProg = "firewall_prog"
)

// loadFirewall returns the embedded CollectionSpec for firewall.
func loadFirewall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FirewallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load firewall: %w", err)
	}

	return spec, err
}

// loadFirewallObjects loads firewall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*firewallObjects
//	*firewallPrograms
//	*firewallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFirewallObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadFirewall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// firewallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallSpecs struct {
	firewallProgramSpecs
	firewallMapSpecs
	firewallVariableSpecs
}

// firewallProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallProgramSpecs struct {
	FirewallProg *ebpf.ProgramSpec `ebpf:"firewall_prog"`
}

// firewallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallMapSpecs struct {
	BlockedIps *ebpf.MapSpec `ebpf:"blocked_ips"`
	Counters   *ebpf.MapSpec `ebpf:"counters"`
	PortPolicy *ebpf.MapSpec `ebpf:"port_policy"`
}

// firewallVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallVariableSpecs struct {
}

// firewallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallObjects struct {
	firewallPrograms
	firewallMaps
	firewallVariables
}

func (o *firewallObjects) Close() error {
	return _FirewallClose(
		&o.firewallPrograms,
		&o.firewallMaps,
	)
}

// firewallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallMaps struct {
	BlockedIps *ebpf.Map `ebpf:"blocked_ips"`
	Counters   *ebpf.Map `ebpf:"counters"`
	PortPolicy *ebpf.Map `ebpf:"port_policy"`
}

func (m *firewallMaps) Close() error {
	return _FirewallClose(
		m.BlockedIps,
		m.Counters,
		m.PortPolicy,
	)
}

// firewallVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallVariables struct {
}

// firewallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallPrograms struct {
	FirewallProg *ebpf.Program `ebpf:"firewall_prog"`
}

func (p *firewallPrograms) Close() error {
	return _FirewallClose(
		p.FirewallProg,
	)
}

func _FirewallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed firewall_bpf.o
var _FirewallBytes []byte
